// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNayZXwQi8eL8a1H2l0OYY_U4sS8cMaLk',
    appId: '1:442828701800:web:bb70f9b2eb6dc263827bdd',
    messagingSenderId: '442828701800',
    projectId: 'chat-app-c8403',
    authDomain: 'chat-app-c8403.firebaseapp.com',
    storageBucket: 'chat-app-c8403.appspot.com',
    measurementId: 'G-8EJB12PB0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEv-XTRBkXtXPl4JU002qcWTOKcIKotKo',
    appId: '1:442828701800:android:66c4bdf61fa18610827bdd',
    messagingSenderId: '442828701800',
    projectId: 'chat-app-c8403',
    storageBucket: 'chat-app-c8403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQIw26Xx2jEJif5ByB98ssxtJcN8z2YY',
    appId: '1:442828701800:ios:d076647463a83afa827bdd',
    messagingSenderId: '442828701800',
    projectId: 'chat-app-c8403',
    storageBucket: 'chat-app-c8403.appspot.com',
    androidClientId: '442828701800-ouf7h0qrum02a0sbb5vd5pgs308fpiin.apps.googleusercontent.com',
    iosClientId: '442828701800-abdrqs2l0j0ffbb21gt2uj9o8fo4ffg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.savia',
  );
}
